version: '3.4'

services:
  microstackdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management

  microstack.products:
    image: ${DOCKER_REGISTRY-}microstackproducts
    build:
      context: .
      dockerfile: MicroStack.Products/Dockerfile

  microstack.sourcing:
    image: ${DOCKER_REGISTRY-}microstacksourcing
    build:
      context: .
      dockerfile: MicroStack.Sourcing/Dockerfile

