version: '3.4'

services:
  microstackdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management

  sourcingsqldb:
    image: mcr.microsoft.com/mssql/server

  microstack.products:
    image: ${DOCKER_REGISTRY-}microstackproducts
    build:
      context: .
      dockerfile: MicroStack.Products/Dockerfile

  microstack.sourcing:
    image: ${DOCKER_REGISTRY-}microstacksourcing
    build:
      context: .
      dockerfile: MicroStack.Sourcing/Dockerfile


  microstack.order:
    image: ${DOCKER_REGISTRY-}microstackorder
    build:
      context: .
      dockerfile: MicroStack.Order/Dockerfile

