version: '3.4'

services:
  microstackdb:
    container_name: microstackdb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports: 
        - "27017:27017" 

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672"

  sourcingsqldb:
    container_name: sourcingsqldb
    ports:
       - "1433:1433"
    environment:
       SA_PASSWORD: "Odb12345678*"
       ACCEPT_EULA: "Y"

  microstack.products:
    container_name: microstackproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ProductDatabaseSettings:ConnectionString=mongodb://microstackdb:27017"
    depends_on:
      - microstackdb
    ports:
      - "8080:8080"
    volumes:
      - ${HOME}/ASP.NET/Https:/home/app/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets



  microstack.sourcing:
    container_name: microstacksourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "SourcingDatabaseSettings:ConnectionString=mongodb://microstackdb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - microstackdb
      - rabbitmq
    ports:
      - "8081:8080"
    volumes:
      - ${HOME}/ASP.NET/Https:/home/app/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets


  microstack.order:
    container_name: microstackorder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:OrderConnection=Server=sourcingsqldb;Database=ORDERDB;User Id=sa;Password=Odb12345678*;TrustServerCertificate=True;"  
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - sourcingsqldb
      - rabbitmq
    ports:
      - "8082:8080"
    volumes:
      - ${HOME}/ASP.NET/Https:/home/app/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets


  microstack.apigateway:
    container_name: microstackapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - microstack.products
      - microstack.sourcing
      - microstack.order
    ports:
      - "5000:8080"
    volumes:
      - ${HOME}/ASP.NET/Https:/home/app/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
